openapi: 3.0.0
info:
  version: 0.0.1
  title: CrashTeam Analytics API
  description:
    $ref: './docs/api.md'
  termsOfService: http://marketdb.pro/terms-of-use/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: 'https://{subdomain}.marketdb.ru/{version}'
    variables:
      subdomain:
        default: api
      version:
        enum:
          - v1
        default: v1
security:
  - bearer: []
paths:
  '/categories':
    $ref: './paths/categories.yaml'
  '/categories/{id}':
    $ref: './paths/categories@{id}.yaml'
  '/categories/{id}/products':
    $ref: './paths/categories@{id}@products.yaml'
  '/products/{productId}':
    $ref: './paths/products@{productId}.yaml'

components:
  securitySchemes:
    bearer:
      $ref: './components/security-schemes/Bearer.yaml'
