type: object
properties:
  mp:
    $ref: ./Marketplace.yaml
  product_mp_id:
    description: Id товара на маркетплейсе
    type: integer
    format: int64
  name:
    description: Имя товара
    type: string
  revenue:
    $ref: ./Revenue.yaml
  sales:
    $ref: ./OrderAmount.yaml
  price:
    $ref: ./Price.yaml
  remainings:
    $ref: ./Remainings.yaml
  rating:
    description: Рейтинг товара
    type: number
    format: double
  number_reviews:
    description: Количество отзывов
    type: integer
    format: int64
  demand:
    description: Спрос
    type: array
    items:
      - $ref: ./Date.yaml
      - $ref: ./OrderAmount.yaml
