type: object
properties:
  seller_link:
    type: string
    description: Уникальный идентификатор (ссылка) на магазин в маркетплейсе
    example: voskpro
  seller_title:
    type: string
    description: Наименование продавца
    example: Воск PRO
